// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsbqfF8S0Onwb1edjTH4FS3DSrI0lKVo',
    appId: '1:712935678121:web:21e766095a06ba492e09b8',
    messagingSenderId: '712935678121',
    projectId: 'socialnetworkflutter-2ceab',
    authDomain: 'socialnetworkflutter-2ceab.firebaseapp.com',
    storageBucket: 'socialnetworkflutter-2ceab.appspot.com',
    measurementId: 'G-TEJVXZ4XN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRv4u3W_Qd_kdp7Nq76plg8KV6A7x8js',
    appId: '1:712935678121:android:ee4a659ef75222b82e09b8',
    messagingSenderId: '712935678121',
    projectId: 'socialnetworkflutter-2ceab',
    storageBucket: 'socialnetworkflutter-2ceab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xTXaaTS7wh5-cuCF3q8ibGQxdorHzYw',
    appId: '1:712935678121:ios:ef4c451f40076ea12e09b8',
    messagingSenderId: '712935678121',
    projectId: 'socialnetworkflutter-2ceab',
    storageBucket: 'socialnetworkflutter-2ceab.appspot.com',
    iosClientId: '712935678121-a1oqneodpanvpvkkstkhimahadjkc4po.apps.googleusercontent.com',
    iosBundleId: 'vn.com.hvloan.socialNetworkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xTXaaTS7wh5-cuCF3q8ibGQxdorHzYw',
    appId: '1:712935678121:ios:ef4c451f40076ea12e09b8',
    messagingSenderId: '712935678121',
    projectId: 'socialnetworkflutter-2ceab',
    storageBucket: 'socialnetworkflutter-2ceab.appspot.com',
    iosClientId: '712935678121-a1oqneodpanvpvkkstkhimahadjkc4po.apps.googleusercontent.com',
    iosBundleId: 'vn.com.hvloan.socialNetworkApp',
  );
}
